defmodule Shopifex.Repo.Migrations.SetupProducts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:products, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:title, :text, null: false)
      add(:description, :text, null: false)
      add(:image_urls, {:array, :text})
      add(:status, :text, null: false, default: "draft")
      add(:handle, :text, null: false)
      add(:type, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:selected_product_variant_id, :uuid)
      add(:archived_at, :utc_datetime_usec)
    end

    create table(:product_variants, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:products) do
      modify(
        :selected_product_variant_id,
        references(:product_variants,
          column: :id,
          name: "products_selected_product_variant_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create unique_index(:products, [:handle], name: "products_handle_index")

    alter table(:product_variants) do
      add(:alias, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :product_id,
        references(:products,
          column: :id,
          name: "product_variants_product_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        )
      )

      add(:archived_at, :utc_datetime_usec)
    end

    create unique_index(:product_variants, [:product_id, :alias],
             name: "product_variants_unique_alias_index"
           )

    create table(:price_variants, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:price, :money_with_currency, null: false)
      add(:compare_at_price, :money_with_currency)
      add(:add_ons, {:array, :map})

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :product_variant_id,
        references(:product_variants,
          column: :id,
          name: "price_variants_product_variant_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        )
      )

      add(:archived_at, :utc_datetime_usec)
    end
  end

  def down do
    drop(constraint(:price_variants, "price_variants_product_variant_id_fkey"))

    drop(table(:price_variants))

    drop_if_exists(
      unique_index(:product_variants, [:product_id, :alias],
        name: "product_variants_unique_alias_index"
      )
    )

    drop(constraint(:product_variants, "product_variants_product_id_fkey"))

    alter table(:product_variants) do
      remove(:archived_at)
      remove(:product_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:alias)
    end

    drop_if_exists(unique_index(:products, [:handle], name: "products_handle_index"))

    drop(constraint(:products, "products_selected_product_variant_id_fkey"))

    alter table(:products) do
      modify(:selected_product_variant_id, :uuid)
    end

    drop(table(:product_variants))

    drop(table(:products))
  end
end
