defmodule Shopifex.Repo.Migrations.References do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:products) do
      modify(:selected_product_variant_id, :uuid)
    end

    create index(:products, [:selected_product_variant_id])

    alter table(:product_variants) do
      modify(:selected_price_variant_id, :uuid)
    end

    create index(:product_variants, [:selected_price_variant_id])
  end

  def down do
    drop_if_exists(index(:product_variants, [:selected_price_variant_id]))

    alter table(:product_variants) do
      modify(:selected_price_variant_id, :uuid)
    end

    drop_if_exists(index(:products, [:selected_product_variant_id]))

    alter table(:products) do
      modify(:selected_product_variant_id, :uuid)
    end
  end
end
